blueprint:
  name: Reset lights to defaults after power restore
  description: >
    When selected lights reconnect after a power cut (state unavailable -> on),
    set brightness and color temperature to default values.
  domain: automation
  input:
    lights:
      name: Lights
      description: Select one or more light entities or groups
      selector:
        entity:
          multiple: true
          domain: light
    brightness_pct:
      name: Brightness %
      default: 50
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"
    color_temp:
      name: Color temperature (mireds)
      default: 350
      selector:
        number:
          min: 150
          max: 500
          mode: slider

mode: restart

trigger:
  - platform: state
    entity_id: !input lights
    from: "unavailable"
    to: "on"

variables:
  lights_list: !input lights
  brightness_value: !input brightness_pct
  color_temp_value: !input color_temp

condition: []

action:
  - delay:
      seconds: 2

  - repeat:
      for_each: "{{ lights_list }}"
      sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ repeat.item }}"
          data:
            brightness_pct: "{{ brightness_value }}"
            color_temp: "{{ color_temp_value }}"
            transition: 1
