blueprint:
  name: Reset lights to defaults after power restore
  description: >
    After lights come back from power loss (unavailable -> on), set default brightness/color.
  domain: automation
  input:
    lights:
      name: Lights (one or more)
      description: Select light entities or a light group
      selector:
        entity:
          multiple: true
          domain: light
    brightness_pct:
      name: Brightness %
      default: 50
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"
    color_temp:
      name: Color temperature (mireds)
      description: Leave empty to skip
      default: 350
      selector:
        number:
          min: 150
          max: 500
          mode: slider

mode: restart

# On déclenche quand CHAQUE entité repasse de 'unavailable' à 'on'
trigger:
  - platform: state
    entity_id: !input lights
    from: "unavailable"
    to: "on"

variables:
  _lights: !input lights
  _brightness: !input brightness_pct
  _ct: !input color_temp

condition: []

action:
  # Petit délai pour laisser le maillage se stabiliser
  - delay:
      seconds: 2

  # On applique les valeurs par défaut
  - service: light.turn_on
    target:
      entity_id: !input lights
    data:
      brightness_pct: "{{ _brightness }}"
      {% raw %}{% if _ct is not none %}{% endraw %}
      color_temp: "{{ _ct }}"
      {% raw %}{% endif %}{% endraw %}
      transition: 1
